version: "3"
services:
  fluentd:
    image: ${DOCKER_REGISTRY}/fluentd:${FLUENTD_VERSION}
    ports:
      - "24224:24224"
      - "24224:24224/udp"
    networks:
      - frontend
  elasticsearch:
    image: elasticsearch:7.17.18
    environment:
      - ELASTIC_CLUSTER=false
      - CLUSTER_NODE_MASTER=true
      - CLUSTER_MASTER_NODE_NAME=es01
      - discovery.type=single-node
    expose:
      - 9200
    ports:
      - "9200:9200"
    networks:
      - frontend
  kibana:
    image: kibana:7.17.18
    ports:
      - "5601:5601"
    networks:
      - frontend
  zipkin:
    image: openzipkin/zipkin:2.21.0
    ports:
      - "9411:9411"
    networks:
      - frontend
      - backend

networks:
  frontend:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.1.0/24
  backend:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.2.0/24
