apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui
  templates:
    metadata:
      name: ui
      labels:
        app: ui
    spec:
      containers:
        - image: rshagochev/ui:2.0
          name: ui
