version: '3.3'
services:
  post_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      - backend
  ui:
    image: ${DOCKER_REGISTRY}/ui:${UI_VERSION}
    ports:
      - ${PUBLIC_PORT}:9292/tcp
    command: "puma -w 2 --debug"
    networks:
      - frontend
  post:
    image: ${DOCKER_REGISTRY}/post:${POST_VERSION}
    networks:
      - backend
      - frontend
  comment:
    image: ${DOCKER_REGISTRY}/comment:${COMMENT_VERSION}
    command: "puma -w 2 --debug"
    networks:
      - backend
      - frontend

volumes:
  post_db:

networks:
  backend:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.1.0/24

  frontend:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.2.0/24
